name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mypy pylint poetry
      - name: Install project dependencies
        run: poetry install
      - uses: psf/black@stable
      - name: mypy
        run: |
          poetry run python -m mypy .
      - name: pylint
        run: poetry run python -m pylint electric_meter_visualizer

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install poetry
        run: python3 -m pip install poetry
      - name: Install project dependencies
        run: poetry install
      - name: Run Tests
        run: poetry run python manage.py test tests
